In [1]:
def f(x = 100, y = 100):
    return (x+y, x-y)
x, y = f(y = 200, x = 100)
print(x, y)

300 -100


In [18]:
import numpy as np
train_set = np.array([1,2,3])
test_set = np.array([[0,1,2], [1,2,3]])
#resulting_set = np.concatenate([train_set, test_set])
#resulting_set = train_set.append(test_set)
res_set = np.vstack([train_set, test_set])
#print(resulting_set)
print(res_set)

[[1 2 3]
 [0 1 2]
 [1 2 3]]


In [12]:
import re
str="""Email_Address,Nickname,Group_Status,Join_Year
aa@aaa.com,aa,Owner,2014
bb@bbb.com,bb,Member,2015
cc@ccc.com,cc,Member,2017
dd@ddd.com,dd,Member,2016
ee@eee.com,ee,Member,2020
"""
for i in re.finditer('([a-zA-Z]+)@([a-zA-Z]+).(com)',str):
    print(i.group(2))
    

aaa
bbb
ccc
ddd
eee


In [59]:
import copy
best_grid = []
max_jump = 0
def isValidMove(grid, x, y):
    if x >= 4 or y >= 3 or x<0 or y<0 or grid[x][y] > -1 :
        return False
    return True

def getValidMoves(grid, x, y, validMoves):
    return [ (i,j) for i,j in validMoves if isValidMove(grid, x+i, y+j) ]

def movesSortedbyNumNextValidMoves(grid, x, y, legalMoves):
    #print("Entering func")
    nextValidMoves = [ (i,j) for i,j in getValidMoves(grid,x,y,legalMoves) ]
    #print("nextValidMoves")
    #print("nextValidMoves:", nextValidMoves)
    # find the number of valid moves for each of the possible valid mode from x,y
    withNumNextValidMoves = [ (len(getValidMoves(grid,x+i,y+j,legalMoves)),i,j) for i,j in nextValidMoves]
    #print("with next valid:",withNumNextValidMoves)
    # sort based on the number so that the one with smallest number of valid moves comes on the top
    return [ (t[1],t[2]) for t in sorted(withNumNextValidMoves) ]

def _solveKnightsTour(grid, x, y, num, legalMoves):
    global max_jump
    global best_grid
    if num == 12:
        return True
    for i,j in getValidMoves(grid,x,y,legalMoves):
        xN,yN = x+i,y+j
        if isValidMove(grid,xN,yN):
            grid[xN][yN] = num
            if(num > max_jump):
                max_jump = num
                best_grid = copy.deepcopy(grid)
            if _solveKnightsTour(grid, xN, yN, num+1, legalMoves):
                return True
            grid[xN][yN] = -1
    return False

def solveKnightsTour(startX=2, startY=0):
    global best_grid
    legalMoves = [(2,1),(2,-1),(-2,1),(-2,-1),(1,2),(1,-2),(-1,2),(-1,-2)]
    #Initializing the grid
    grid = [ x[:] for x in [[-1]*3]*4 ]
    grid[startX][startY] = 0
    if _solveKnightsTour(grid,startX,startY,1,legalMoves):
        print("final:", best_grid)
        
    else:
        print(best_grid)

def jumpy_knight(board):
    for i in range(len(board)):
        for j in range(len(board[i])):
            if(board[i][j] == 0):
                solveKnightsTour(i, j)
#solveKnightsTour(8)
test_board_1 = [[0],[ ],[ ],
 				[ ],[ ],[ ],
				[ ],[ ],[ ],
				[ ],[ ],[ ]]
jumpy_knight(test_board_1)

final: [[0, 7, 2], [3, 10, 5], [6, 1, 8], [9, 4, 11]]
